services:

  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    ports:
      - 3306:3306
    networks:
      - default

  adminer:
    image: adminer
    restart: always
    ports:
     - 8080:8080
    networks:
     - default

networks:
  default:
    driver: bridge
